export const toolbox_group = "toolbox"
export const hidden_class = "hidden"
export const hidden_important_class = "hidden-important"
export const drop_target_class = "drop-target"
export const target_class = "target"
